### ISSUE TITLE
Not PHP 7.0 compatible

### ISSUE THREAD

**Issue by sgehrman** [gndev/shortcodes-ultimate#42]
Install https://wordpress.org/plugins/php-compatibility-checker/

It lists Shortcodes Ultimate as not being php7 compatible because of 
##  44 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'bool' (since version 7.0)

It would be great if you could fix it and respost.  Thanks.

-steve

**Comment by le717** [comment]
I get a different PHP 7.0 error using the aforementioned plugin.

```
FILE: /home8/mySite/public_html/wp-content/plugins/shortcodes-ultimate/inc/core/tools.php
-------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------
 681 | ERROR | Using 'break' outside of a loop or switch structure is invalid
and will throw a fatal error since PHP 7.0
-------------------------------------------------------------------------------------------
```
This is the only thing stopping me from upgrading my site to  PHP 7.0. :(

**Comment by Hube2** [comment]
I'm curious about this, I get the same report as @le717 

The break in question in inside of an if that is inside a foreach. The break is inside of the loop. Does PHP 7.0 no longer let you conditionally break out of a loop?

**Comment by Hube2** [comment]
I was concerned due to the fact that I use this on many sites and plan to continue using it. The error reported is a false positive. After doing a search I have found many reports of this on many plugins. The tool does not understand the if statements in most cases. This tool is good for giving you an idea of where to check the code just to be sure but I would never take what it told me as 100% accurate without actually looking at the code in question myself.
